import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        mono: ["var(--font-mono)", "ui-monospace", "SFMono-Regular", "monospace"],
        "cb-display": ['"Coinbase Display"', "Inter", "-apple-system", "system-ui", "sans-serif"],
        "cb-sans": ['"Coinbase Sans"', "Inter", "-apple-system", "system-ui", "sans-serif"],
        "cb-mono": ['"Coinbase Mono"', "JetBrains Mono", "var(--font-mono)", "monospace"],
      },
      colors: {
        "cb-primary": "#0052ff",
        "cb-primary-active": "#003ecc",
        "cb-primary-disabled": "#a8b8cc",
        "cb-ink": "#0a0b0d",
        "cb-body": "#5b616e",
        "cb-body-strong": "#0a0b0d",
        "cb-muted": "#7c828a",
        "cb-muted-soft": "#a8acb3",
        "cb-hairline": "#dee1e6",
        "cb-hairline-soft": "#eef0f3",
        "cb-canvas": "#ffffff",
        "cb-surface-soft": "#f7f7f7",
        "cb-surface-card": "#ffffff",
        "cb-surface-strong": "#eef0f3",
        "cb-surface-dark": "#0a0b0d",
        "cb-surface-dark-elevated": "#16181c",
        "cb-on-primary": "#ffffff",
        "cb-on-dark": "#ffffff",
        "cb-on-dark-soft": "#a8acb3",
        "cb-semantic-up": "#05b169",
        "cb-semantic-down": "#cf202f",
        "cb-accent-yellow": "#f4b000",
      },
      borderRadius: {
        "cb-none": "0px",
        "cb-xs": "4px",
        "cb-sm": "8px",
        "cb-md": "12px",
        "cb-lg": "16px",
        "cb-xl": "24px",
        "cb-pill": "100px",
        "cb-full": "9999px",
      },
      spacing: {
        "cb-xxs": "4px",
        "cb-xs": "8px",
        "cb-sm": "12px",
        "cb-base": "16px",
        "cb-md": "20px",
        "cb-lg": "24px",
        "cb-xl": "32px",
        "cb-xxl": "48px",
        "cb-section": "96px",
      },
      fontSize: {
        "cb-display-mega": ["80px", { lineHeight: "1.0", letterSpacing: "-2px", fontWeight: "400" }],
        "cb-display-xl": ["64px", { lineHeight: "1.0", letterSpacing: "-1.6px", fontWeight: "400" }],
        "cb-display-lg": ["52px", { lineHeight: "1.0", letterSpacing: "-1.3px", fontWeight: "400" }],
        "cb-display-md": ["44px", { lineHeight: "1.09", letterSpacing: "-1px", fontWeight: "400" }],
        "cb-display-sm": ["36px", { lineHeight: "1.11", letterSpacing: "-0.5px", fontWeight: "400" }],
        "cb-title-lg": ["32px", { lineHeight: "1.13", letterSpacing: "-0.4px", fontWeight: "400" }],
        "cb-title-md": ["18px", { lineHeight: "1.33", letterSpacing: "0", fontWeight: "600" }],
        "cb-title-sm": ["16px", { lineHeight: "1.25", letterSpacing: "0", fontWeight: "600" }],
        "cb-body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "cb-body-strong": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "700" }],
        "cb-body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "cb-caption": ["13px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "cb-caption-strong": ["12px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "600" }],
        "cb-number": ["18px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
        "cb-button": ["16px", { lineHeight: "1.15", letterSpacing: "0", fontWeight: "600" }],
        "cb-nav-link": ["14px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
      },
      boxShadow: {
        "cb-hover": "0 4px 12px rgba(0, 0, 0, 0.04)",
      },
    },
  },
  plugins: [],
};

export default config;
