import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        mono: ["var(--font-mono)", "ui-monospace", "SFMono-Regular", "monospace"],
        "rv-display": ['"Aeonik Pro"', '"Inter Display"', '"General Sans"', "Söhne", "-apple-system", "system-ui", "sans-serif"],
        "rv-sans": ['"Inter"', "-apple-system", "system-ui", '"Segoe UI"', "Roboto", "Helvetica", "Arial", "sans-serif"],
      },
      colors: {
        "rv-primary": "#494fdf",
        "rv-primary-bright": "#4f55f1",
        "rv-primary-deep": "#3a40c4",
        "rv-on-primary": "#ffffff",
        "rv-ink": "#191c1f",
        "rv-body": "#1f2226",
        "rv-charcoal": "#3a3d40",
        "rv-mute": "#505a63",
        "rv-ash": "#5c5e60",
        "rv-stone": "#8d969e",
        "rv-faint": "#c9c9cd",
        "rv-on-dark": "#ffffff",
        "rv-canvas-light": "#ffffff",
        "rv-canvas-dark": "#000000",
        "rv-surface-soft": "#f4f4f4",
        "rv-surface-card": "#ffffff",
        "rv-surface-deep": "#0a0a0a",
        "rv-surface-elevated": "#16181a",
        "rv-hairline-light": "#e2e2e7",
        "rv-hairline-strong": "#191c1f",
        "rv-accent-teal": "#00a87e",
        "rv-accent-blue-link": "#376cd5",
        "rv-accent-light-blue": "#007bc2",
        "rv-accent-light-green": "#428619",
        "rv-accent-yellow": "#b09000",
        "rv-accent-warning": "#ec7e00",
        "rv-accent-pink": "#e61e49",
        "rv-accent-danger": "#e23b4a",
        "rv-accent-brown": "#936d62",
      },
      borderRadius: {
        "rv-none": "0px",
        "rv-sm": "8px",
        "rv-md": "12px",
        "rv-lg": "20px",
        "rv-xl": "28px",
        "rv-full": "9999px",
      },
      spacing: {
        "rv-xxs": "4px",
        "rv-xs": "6px",
        "rv-sm": "8px",
        "rv-md": "14px",
        "rv-lg": "16px",
        "rv-xl": "24px",
        "rv-xxl": "32px",
        "rv-xxxl": "48px",
        "rv-block": "80px",
        "rv-section": "88px",
        "rv-band": "120px",
      },
      fontSize: {
        "rv-display-xxl": ["136px", { lineHeight: "1.0", letterSpacing: "-2.72px", fontWeight: "500" }],
        "rv-display-xl": ["80px", { lineHeight: "1.0", letterSpacing: "-0.8px", fontWeight: "500" }],
        "rv-display-lg": ["48px", { lineHeight: "1.21", letterSpacing: "-0.48px", fontWeight: "500" }],
        "rv-display-md": ["40px", { lineHeight: "1.2", letterSpacing: "-0.4px", fontWeight: "500" }],
        "rv-heading-lg": ["32px", { lineHeight: "1.19", letterSpacing: "-0.32px", fontWeight: "500" }],
        "rv-heading-md": ["24px", { lineHeight: "1.33", letterSpacing: "0", fontWeight: "500" }],
        "rv-heading-sm": ["20px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
        "rv-body-lg": ["18px", { lineHeight: "1.56", letterSpacing: "-0.09px", fontWeight: "400" }],
        "rv-body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0.24px", fontWeight: "400" }],
        "rv-body-md-bold": ["16px", { lineHeight: "1.5", letterSpacing: "0.16px", fontWeight: "600" }],
        "rv-body-sm": ["14px", { lineHeight: "1.43", letterSpacing: "0", fontWeight: "400" }],
        "rv-button-lg": ["20px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
        "rv-button-md": ["16px", { lineHeight: "1.5", letterSpacing: "0.24px", fontWeight: "600" }],
        "rv-button-sm": ["14px", { lineHeight: "1.43", letterSpacing: "0", fontWeight: "600" }],
        "rv-caption": ["13px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
